format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_apps_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_CLIENT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_SERVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_SERVER_V2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DNS_CLIENT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_SNTP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '21', id: tcpip_apps_config}
