format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: FREERTOS_DAEMON_TASK_STARTUP_HOOK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: File
    attributes: {id: FREERTOS_HEAP_1_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_HEAP_3_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_INCLUDE_UXTASKGETSTACKHIGHWATERMARK}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_INCLUDE_XTASKGETHANDLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: FREERTOS_MAX_PRIORITIES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Integer
    attributes: {id: FREERTOS_MAX_TASK_NAME_LEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '26'}
  - type: Combo
    attributes: {id: FREERTOS_MEMORY_MANAGEMENT_CHOICE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Heap_3}
  - type: Integer
    attributes: {id: FREERTOS_MINIMAL_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '512'}
  - type: Integer
    attributes: {id: FREERTOS_PERIPHERAL_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '100000000'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_QUEUE_LENGTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '10'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_PRIORITY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '3'}
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_STACK_DEPTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '256'}
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_RECURSIVE_MUTEXES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_TIMERS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SET_RTOS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: FreeRTOS}
- type: ElementPosition
  attributes: {x: '29', y: '66', id: FreeRTOS}
